In [1]:
%pip install pandas
%pip install duckdb

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: duckdb in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (1.3.2)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import duckdb
import os
from datetime import datetime

In [3]:

con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [28]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}',sep=';')
df['nome_do_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_do_arquivo,data_ingestao
0,10004,SERRA,BT10,100,200,z0019_2.csv,2025-07-30 12:26:51.139069
1,10005,MACHADO,BT10,100,100,z0019_2.csv,2025-07-30 12:26:51.139069
2,10003,PREGO,BT10,100,60,z0019_2.csv,2025-07-30 12:26:51.139069

In [29]:
con.execute('''
            CREATE TABLE IF NOT EXISTS bronze_produtos (
            NATBR VARCHAR,
            MAKTX VARCHAR,
            WERKS VARCHAR,
            MAINS VARCHAR,
            LABST VARCHAR,
            nome_do_arquivo VARCHAR,
            data_ingestao TIMESTAMP

            )
''')

In [30]:
con.execute('INSERT INTO bronze_produtos SELECT * FROM df')

In [34]:
resultado = con.execute('''SELECT * FROM bronze_z0019''').fetchdf()
resultado.head(6)

,NATBR,MAKTX,WERKS,MAINS,LABST,nome_do_arquivo,data_ingestao
0,10001,PARAFUSO,BT10,100,100,z0019_1.csv,2025-07-30 12:19:29.823397
1,10002,MARTELO,BT50,100,1500,z0019_1.csv,2025-07-30 12:19:29.823397
2,10003,PREGO,BT10,100,50,z0019_1.csv,2025-07-30 12:19:29.823397
3,10004,SERRA,BT10,100,200,z0019_2.csv,2025-07-30 12:26:51.139069
4,10005,MACHADO,BT10,100,100,z0019_2.csv,2025-07-30 12:26:51.139069
5,10003,PREGO,BT10,100,60,z0019_2.csv,2025-07-30 12:26:51.139069

In [33]:
con.execute('''ALTER TABLE bronze_produtos RENAME TO bronze_z0019''')

In [35]:
con.close()